FROM saltstack/ubuntu-14.04
MAINTAINER heweijun "heweijun@iciyun.com"

CMD "mkdir -p /usr/servers"
CMD "cd /usr/servers"

##RUN "apt-get install libreadline-dev -y"
##RUN "apt-get install libncurses5-dev -y"
##RUN "apt-get install libpcre3-dev  -y" 
##RUN "apt-get install libssl-dev -y"
##RUN "apt-get install  perl -y"

CMD "wget http://openresty.org/download/ngx_openresty-1.7.7.2.tar.gz"

CMD "tar -xzvf ngx_openresty-1.7.7.2.tar.gz"



